development:
  adapter: postgresql
  encoding: unicode
  database: sample_dev
  pool: 5
  host: localhost
  username: thomas
  password: postgres
  timeout: 5000

test:
  adapter: postgresql
  database: sample_test
  pool: 5
  host: localhost
  username: thomas
  password: postgres
  timeout: 5000

production:
  adapter: postgresql
  database: sample_prod
  pool: 5
  host: localhost
  username: thomas
  password:
  timeout: 5000
